### ISSUE TITLE
YOLO5-Face 모듈 추가

### ISSUE THREAD

**Issue by junghyun-avikus** [avikus-ai/detect_train#6]
**목적** : 작은 물체를 잡기 위해 기존 YOLO의 아키텍쳐를 바꾼 모델이며, 이를 구현하기 위한 common.py 에 모듈 추가 및 gen_wts 추가

**Comment by youngjae-avikus** [comment]
COCO pretrained 모델 640 이미지 사이즈, yolov5s-face 만드는 작업 진행 

```bash
python -m torch.distributed.run --nproc_per_node 4 train.py --batch 256 --cfg models/yolov5s_face.yaml --weights yolov5s.pt --data coco.yaml --img 640 --epochs 300 --project HiNAS_PRETRAINED --name yolov5sface-coco-640-med --device 0,1,2,3 --hyp data/hyps/hyp.scratch-med.yaml
```

[ultralytics](https://github.com/ultralytics/yolov5#pretrained-checkpoints)
ultralytics coco pretrained mAP(IoU=0.5)=56.8 나오는지 확인해볼 것

**Comment by youngjae-avikus** [comment]
yolov5sface640 pretrained 모델 만드는 과정에서 epoch 65까지 mAP 0.459까지 나오고 더디길래, 종료하고 나서
ultralytics coco pretrained mAP(IoU=0.5)=56.8을 검증하기 위해서 yolov5s.yaml로 돌리는데 yolov5sface640 pretrained 모델처럼 더디긴 하는데, 계속 돌리니 조금씩 mAP는 상승하네요

```bash
 python -m torch.distributed.run --nproc_per_node 4 train.py --batch 256 --cfg models/yolov5s.yaml --weights '' --data coco.yaml --img 640 --epochs 300 --project Train_COCO --name coco-scratch-v5s640 --device 0,1,2,3 --hyp data/hyps/hyp.scratch-low.yaml
```

그래서 제대로 pretrained 모델 만드려면 300번까지는 돌려야겠네요

**Comment by youngjae-avikus** [comment]
official coco pretrained
```bash
python val.py --weights yolov5s.pt --data/coco-cocoapi.yaml --img 640
```

![image](https://user-images.githubusercontent.com/99321359/217971571-fd044012-91e6-44ca-a68c-b1a9d2b89a46.png)

---
yolov5s-face coco pretrained
```bash
python val.py --weights yolov5sface-coco-640 --data/coco-cocoapi.yaml --img 640
```

![image](https://user-images.githubusercontent.com/99321359/217971897-d9f95ce8-fc8f-490b-a2b2-a4553ca78c6f.png)
